### ISSUE TITLE
Problem adapting the tutorial to use ubuntu 15.10

### ISSUE THREAD

**Issue by wasadigi** [hashicorp/atlas-packer-vagrant-tutorial#10]
Hi,

I am starting to use packer and atlas. I have managed to go through the tutorial and to build my vagrant box on atlas. Great stuff. Now, I would like to adapt the template to use the latest version of ubuntu. When I simply change the iso_url and the iso_checksum to point to the 15.10 files, the build process gets stuck on "Waiting for ssh to be available...".

I have tested the same modification with ubuntu 15.04 and in this case, it works fine.

I have seen in mitchellh/vagrant#6683 that network management has significantly changed in ubuntu 15.10, causing issues with Vagrant. Seems like these issues could be solved in Vagrant 1.8. Note that I have managed to build the box locally (with vagrant 1.8.1). So I am suspecting that the vagrant infrastructure on atlas does not incorporate these fixes yet.

Looking for packer templates in GitHub repos, I have seen that most contributors provide scripts to build the images locally. I have not found repos that provide examples where the images are built on atlas.

Do you know of such examples, ideally with support for ubuntu 15.10?
Do you know what is needed in order to build a ubuntu 15.10 vagrant box on atlas? Is that possible?

Many thanks!

**Comment by kikitux** [comment]
Hello @wasadigi 

Will be possible you send an email to support at hashicorp.com with a zip file of your project for review?

Thanks
Alvaro

**Comment by wasadigi** [comment]
Thanks for the feedback @kikitux. I have a fork of the original atlas-packer tutorial, with two templates (one for ubuntu 15.04 that works and one for ubuntu 15.10 that does not work). I will also send an email to support. Here is the repo, for reference:
https://github.com/wasadigi/atlas-packer-vagrant-tutorial

**Comment by wasadigi** [comment]
Thanks to packer templates found in several GitHub repos, I was able to fix the issues (both by fixing the template and the supporting pre-seed file). I have committed the changes in https://github.com/wasadigi/atlas-packer-vagrant-tutorial/commit/74cd71170542fdbb7487f4a39533019c80c1f372
