### ISSUE TITLE
aws creds

### ISSUE THREAD

**Issue by curtismitchell** [hashicorp/atlas-packer-vagrant-tutorial#4]
Hey -

In case this isn't intentional - there are a set of [aws credentials](https://github.com/hashicorp/atlas-packer-vagrant-tutorial/blob/master/scripts/download_go_service.sh#L20) in this repository.  As part of the tutorial, users are directed to clone this repo.  Hopefully, the credentials that come along with it, are restricted and intentional.

**Comment by pearkes** [comment]
Thank you, these keys have been revoked. You would have had access to our binary store for internal services! Appreciate it.
