### ISSUE TITLE
which post-processors?

### ISSUE THREAD

**Issue by rvosa** [hashicorp/atlas-packer-vagrant-tutorial#6]
Hi,

sorry, this is not really a bug report or anything, just a question: if I want to be able to do `packer push -create template.json` such that the end result is a vagrant box (let's say that in the template.json it's called `foo/bar`) in the vagrant cloud (so that it can be instantiated with `vagrant init foo/bar`), which post-processors do I need to use? Just the vagrant one? Or vagrant and atlas? 

Also, where should I really be asking this? You guys have been very nice in responding on twitter - and hopefully here also - but should I perhaps be on a mailing list or something? Don't wanna abuse your kindness. Thanks for the - potentially - great tools! Hope I get them to work :)

Rutger

**Comment by KFishner** [comment]
Hey Rutger!

For the future, support@hashicorp.com is the best avenue to ask questions like these. Or we have Google Groups for each project. For example, the Packer Google Group: https://groups.google.com/forum/#!forum/packer-tool

As for your question, you need to use both the `vagrant` post-processor and the `atlas` post-processor. The `vagrant` one first takes the Virtualbox or VMware image and turns it into a Vagrant box, and the `atlas` one takes the Vagrant box and uploads it to Atlas.
