### ISSUE TITLE
Vagrant init error

### ISSUE THREAD

**Issue by DinisCruz** [hashicorp/atlas-packer-vagrant-tutorial#7]
Hi after following the tutorial and getting to this page

![image](https://cloud.githubusercontent.com/assets/656739/7666766/74b871c8-fbe8-11e4-872e-7dd4e621b18c.png)

I had this error when running `vagrant init DinisCruz/packer-vagrant-tutorial --provider virtualbox`

![image](https://cloud.githubusercontent.com/assets/656739/7666760/6c552828-fbe8-11e4-887e-0dfddc69223c.png)

**Comment by sethvargo** [comment]
This has been fixed. Thank you for reporting!
