### ISSUE TITLE
Javascript error in step 4

### ISSUE THREAD

**Issue by ashnur** [hashicorp/atlas-packer-vagrant-tutorial#8]
When clicking `Verify progress`

`Uncaught Error: Nothing handled the action 'goToUI'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble.`

**Comment by markupboy** [comment]
So sorry about that. We're getting this fixed up right now and the fix should be deployed shortly. Will update this ticket when it's finished up.

**Comment by KFishner** [comment]
This is fixed!
