### ISSUE TITLE
Simpler license?

### ISSUE THREAD

**Issue by jgonera** [hashicorp/atlas-packer-vagrant-tutorial#9]
Since this is only an example for a tutorial, could we use MIT/BSD/Creative Commons or even http://www.wtfpl.net/ ? I don't think anyone wants to read a 15KB `LICENSE` file just to write their Packer template ;)

**Comment by sethvargo** [comment]
Hi @jgonera 

The license is the MPL and it's the license we use for all our open source materials. Unfortunately that's what the lawyers require. Sorry!
